config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords]
  resources :games do
    member do
      get :compute
    end
    resources :statistics
    resources :tournaments
    resources :participants
  end

  root 'home#show'
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  has_many :results, dependent: :destroy
  belongs_to :game
  geocoded_by :location
  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.city = geo.city
      obj.state = geo.state
      obj.sub_state = geo.sub_state
      obj.country = geo.country
    end
  end
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
  after_validation :reverse_geocode
  after_validation :update_indexes

  has_many :character_participants, dependent: :destroy
  has_many :characters, through: :character_participants

  has_many :team_participants, dependent: :destroy
  has_many :teams, through: :team_participants

  include FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]
  
  def slug_candidates
    [
      :name,
      [:name, :city],
      [:name, :id],
    ]
  end

  def twitter_link
    twitter_id = twitter
    if twitter_id
      twitter_id = twitter_id[1..-1] if twitter_id.first == '@'
      "http://www.twitter.com/#{twitter_id}"
    end
  end

  def compute_score
    self.update_attribute(:score, results.compute)
  end

  def global_rank
    game_participants.ranking(score)
  end

  def country_rank
    game_participants.from_country(country).ranking(score)
  end

  def state_rank
    game_participants.from_state(country, state).ranking(score)
  end

  def sub_state_rank
    game_participants.from_sub_state(country, state, sub_state).ranking(score)
  end

  def city_rank
    game_participants.from_city(country, state, sub_state, city).ranking(score)
  end

  def character_rank(character_name)
    character = Character.where(game_id: game.id).find_by_slug(character_name)
    character ? character.participants.ranking(score) : global_rank
  end

  def next_target
    game_participants.where('score > ?', score).order('score asc').first if location
  end

  def training_partners
    return city_buddies      if city      && city_buddies.count      > 0
    return sub_state_buddies if sub_state && sub_state_buddies.count > 0
    return state_buddies     if state     && state_buddies.count     > 0
    return country_buddies   if country   && country_buddies.count   > 0
    return world_buddies
  end

  def self.clean
    where('id not in (select distinct(participant_id) FROM results)').map(&:destroy)
  end

  def merge_process
    if participant = game_participants.find_by_name(self.name)
      results.each { |r| r.update_attribute(:participant_id, participant.id) }
      self.reload.destroy
      participant.compute_score
    end
  end

  def self.ranking(score)
    where('score > ?', score).count + 1
  end

  def character_names
    characters.pluck(:slug).join("\n")
  end

  def team_names
    teams.pluck(:name).join("\n")
  end

  def country_code
    CountryCodesList.mapping(country)
  end

  private

  def city_buddies
    game_participants.from_city(country, state, sub_state, city).get_close_buddies(id, score)
  end

  def sub_state_buddies
    game_participants.from_sub_state(country, state, sub_state).get_close_buddies(id, score)
  end
  
  def state_buddies
    game_participants.from_state(country, state).get_close_buddies(id, score)
  end
  
  def country_buddies
    game_participants.from_country(country).get_close_buddies(id, score)
  end

  def world_buddies
    game_participants.get_close_buddies(id, score)
  end

  def self.from_city(country, state, sub_state, city)
    where(country: country, state: state, sub_state: sub_state, city: city)
  end

  def self.from_sub_state(country, state, sub_state)
    where(country: country, state: state, sub_state: sub_state)
  end

  def self.from_state(country, state)
    where(country: country, state: state)
  end

  def self.from_country(country)
    where(country: country)
  end

  def self.get_close_buddies(id, score)
    ordered_collection = self.order('score desc')
    better = ordered_collection.where('score > ?', score).last(2)
    tie = ordered_collection.where('id <> ? and score = ?', id, score).sample(2)
    worst = ordered_collection.where('score < ?', score).first(2)
    tie + better + worst
  end

  def self.filter_by_params(params)
    game = Game.find(params[:game_id])
    participants = Participant.where(game_id: game.id)

    if (character = game.characters.find_by_slug(params[:character]))
      participants = participants.joins(:characters).where(characters: {id: character.id})
      participants = participants.joins(:character_participants).where(character_participants: {rank: 1}).uniq if params[:main]
    end
    if params[:country] == 'Europe'
      participants = participants.where(country: CountryCodesList.europe) if params[:country] == 'Europe'
    else
      participants = participants.where(country: params[:country]) if params[:country]
      participants = participants.where(state: params[:state]) if params[:state]
      participants = participants.where(sub_state: params[:sub_state]) if params[:sub_state]
      participants = participants.where(city: params[:city]) if params[:city]
    end
    if (team = game.teams.find_by_slug(params[:team]))
      participants = participants.joins(:teams).where(teams: {id: team.id})
    end
    participants
  end

  def game_participants
    Participant.where(game_id: game.id)
  end

  def update_indexes
    self.update_attribute(:characters_index, self.character_names.gsub("\n", ','))
    self.update_attribute(:teams_index, self.teams.map{ |c| c.slug + ';' + c.name }.join(','))
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_filter :authenticate_admin!, only: [:edit, :update]

  def index
    @game = Game.find(params[:game_id])

    respond_to do |format|
      format.html
      format.json do
        @participants = @game.participants.filter_by_params(params)
        json_participants = get_json_for_angular
        render json: json_participants
      end
    end
  end

  def edit
    @participant = Participant.find(params[:id])
    @results = @participant.results
    @game = Game.find(params[:game_id])
  end

  def show
    @participant = Participant.find(params[:id])
    @results = @participant.results
    @game = Game.find(params[:game_id])
  end

  def update
    @game = Game.find(params[:game_id])
    @participant = Participant.find(params[:id])
    @attributes = permitted_params[:participant]
    add_characters_to_participant
    add_teams_to_participant

    if @attributes[:name].present? && @participant.name != @attributes[:name]
      @participant.name = @attributes[:name]
      @participant.merge_process if Participant.find_by_name(@participant.name)
    end
    
    @participant.attributes = @attributes
    if !@participant.persisted? || @participant.save 
      redirect_to [@game, @participant]
    else
      render :edit
    end
  end

  private

  def add_teams_to_participant
    @participant.teams = []
    @attributes.delete(:team_names).split("\n").map(&:strip).each do |name|
      unless team = Team.where(game_id: @game.id).find_by_slug(name.parameterize)
        team = Team.create(game_id: @game.id, name: name)        
      end
      @participant.teams << team
    end
  end

  def add_characters_to_participant
    @participant.characters = []
    rank = 1
    @attributes.delete(:character_names).split("\n").map(&:strip).each do |name|
      char = Character.where(game_id: @game.id).find_by_slug(name.parameterize)
      CharacterParticipant.create(rank: rank, participant_id: @participant.id, character_id: char.id) unless char.blank?
      rank += 1
    end
  end

  def get_json_for_angular
    game_slug = @game.slug
    character_img_matcher = {}
    @game.characters.each { |c| character_img_matcher[c.slug] = ActionController::Base.helpers.asset_path("#{game_slug}/#{c.slug}.png")}
    global_rank = 1
    rank = 1
    @participants.order(score: :desc, name: :asc).map do |participant|
      rank = global_rank if @old_score && @old_score > participant.score
      global_rank += 1
      @old_score = participant.score
      participant_json = participant.attributes.merge(rank: rank)
      participant.characters_index.split(',').each_with_index do |cp, i|
        participant_json["character#{i + 1}_slug"] = cp
        participant_json["character#{i + 1}_img"] = character_img_matcher[cp]
      end if participant.characters_index
      participant.teams_index.split(',').each_with_index do |team, i|
        participant_json["team#{i + 1}_slug"] = team.split(';').first
        participant_json["team#{i + 1}_name"] = team.split(';').last
      end if participant.teams_index
      participant_json['country_code'] = CountryCodesList.mapping(participant.country)
      participant_json['game_slug'] = game_slug
      participant_json
    end
  end

  def permitted_params
    params.permit(participant: [
      :name,
      :location,
      :twitter,
      :youtube,
      :wiki,
      :character_names,
      :team_names
    ])
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_name_title.html.slim
h5.soft.text--center
  = @participant.name

app/views/participants/_ranking_title.html.slim
h4.soft--bottom.text--center
  - if params[:city]
    = params[:city] + ' Ranking'
  - elsif params[:sub_state]
    = params[:sub_state] + ' Ranking'
  - elsif params[:state]
    = params[:state] + ' Ranking'
  - elsif params[:country]
    = params[:country] + ' Ranking'
    .small.soft--bottom.text--center=> link_to 'Whole Europe ?', game_participants_path(@game, country: 'Europe') if CountryCodesList.europe.include?(params[:country])

  - elsif params[:character] && Character.where(game_id: @game.id).find_by_slug(params[:character])
    => link_to Character.where(game_id: @game.id).find_by_slug(params[:character]).name + ' Ranking', game_participants_path(@game, character: params[:character])
    .small.soft--bottom.text--center=> link_to 'Main only ?', game_participants_path(@game, character: params[:character], main: true) unless params[:main]
  - elsif params[:team] && Team.where(game_id: @game.id).find_by_slug(params[:team])
    => link_to Team.where(game_id: @game.id).find_by_slug(params[:team]).name + ' Ranking', game_participants_path(@game, team: params[:team])
  - else
    = 'GLOBAL RANKING'

app/views/participants/edit.html.haml
= render 'games/header'
= render partial: 'name_title'
= render 'games/menu'

.soft
  .max-readable-width
    .grid__item.one-half.text--left>
      .soft
        = simple_form_for [@game, @participant] do |f|
          = f.input :name, required: true
          = f.input :twitter
          = f.input :youtube
          = f.input :wiki
          = f.input :location, input_html: { id: 'gmaps-input-address', autocomplete: 'off' }, placeholder: 'Start typing a place...'
          = f.input :character_names, as: :text, placeholder: "Fox\nPeach\n..."
          .small
            = "#{Character.where(game_id: @game.id).pluck(:slug).join(', ')}"
          = f.input :team_names, as: :text, placeholder: "EG\nCurse\nLiquid`"
    
          = f.button :submit
    .grid__item.one-half.text--right>
      .soft
        = "Score: #{@participant.score}"
        %br
        %br
        - link = 'Global rank: ' + @participant.global_rank.ordinalize
        = link_to link, game_participants_path(@game)
        - if @participant.country
          %br
          - link = @participant.country + ' rank: ' + @participant.country_rank.ordinalize
          = link_to link, game_participants_path(@game, country: @participant.country)
        - if @participant.state
          %br
          - link = @participant.state + ' rank: ' + @participant.state_rank.ordinalize
          = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state)
        - if @participant.sub_state
          %br
          - link = @participant.sub_state + ' rank: ' + @participant.sub_state_rank.ordinalize
          = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state, sub_state: @participant.sub_state)
        - if @participant.city
          %br
          - link = @participant.city + ' rank: ' + @participant.city_rank.ordinalize
          = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state, sub_state: @participant.sub_state, city: @participant.city)
        - if next_target = @participant.next_target
          %br
          = "#{@participant.name}'s next target is "
          = link_to next_target.name, [:edit, @game, next_target]
        - if training_partners = @participant.training_partners
          %br
          = 'He should train with '
          - training_partners.each do |player|
            = link_to player.name + ' ', [:edit, @game, player]

app/views/participants/index.html.haml
= render 'games/header'
= render partial: 'ranking_title'
= render 'games/menu'


%ul{class: 'f16', style: 'margin-left: 0px;'}
  .soft
    .max-readable-width.text--center
      %div{:"ng-app" => "application", :"ng-controller" => "ParticipantsController"}
        .form-search.form-inline
          %input{type: "text", "ng-model" => "search.$", class: 'rounded-input', placeholder: "Search for a player, a country or a character here...".html_safe}
          %br

        .text--left
          %i.fa.fa-gamepad
          {{ filteredParticipants().length }} Players
        

        .grid{:'ng-repeat' => 'participant in filteredParticipants() | startFrom:currentPage*pageSize | limitTo:pageSize'}
          %div{style: 'border-top : 1px solid #CFCACA; padding-top: 9px;'}
          .grid__item.one-eighth.text--left>
            {{ participant.rank }}
          .grid__item.one-half.text--left>
            %a{:'ng-if' => 'participant.country_code', :'ng-href' => '/games/{{participant.game_slug}}/participants?country={{participant.country}}', class: 'flag {{participant.country_code}}', style: 'padding-top:0px;'}
              &nbsp&nbsp&nbsp
            %icon{:'ng-if' => 'participant.country_code == null'}
              = image_tag('flag_none2.png', style: 'padding-bottom: 7px;')

            &nbsp

            %a{:"ng-if" => "participant.team1_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?team={{participant.team1_slug}}"}
              {{participant.team1_name}}
            %a{:"ng-if" => "participant.team2_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?team={{participant.team2_slug}}"}
              {{participant.team2_name}}
            %a{:"ng-if" => "participant.team3_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?team={{participant.team3_slug}}"}
              {{participant.team3_name}}

            %icon{:"ng-if" => "participant.team1_slug"}
              |
            %a.super-heavy-font{:"ng-href" => "/games/{{participant.game_slug}}/participants/{{participant.slug}}"}
              {{ participant.name }}
          .grid__item.one-quarter.text--left>
            
            %a{:"ng-if" => "participant.character1_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?character={{participant.character1_slug}}"}
              %img{alt: "{{participant.character1_slug}}", :"ng-src" => "{{participant.character1_img}}", width: 15}

            %a{:"ng-if" => "participant.character2_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?character={{participant.character2_slug}}"}
              %img{alt: "{{participant.character2_slug}}", :"ng-src" => "{{participant.character2_img}}", width: 15}

            %a{:"ng-if" => "participant.character3_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?character={{participant.character3_slug}}"}
              %img{alt: "{{participant.character3_slug}}", :"ng-src" => "{{participant.character3_img}}", width: 15}

            %a{:"ng-if" => "participant.character4_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?character={{participant.character4_slug}}"}
              %img{alt: "{{participant.character4_slug}}", :"ng-src" => "{{participant.character4_img}}", width: 15}

            %a{:"ng-if" => "participant.character5_slug", :"ng-href" => "/games/{{participant.game_slug}}/participants?character={{participant.character5_slug}}"}
              %img{alt: "{{participant.character5_slug}}", :"ng-src" => "{{participant.character5_img}}", width: 15}
          .grid__item.one-eighth.text--left>
            = ''
          %div{style: 'padding-bottom: 6px;'}


        %button{:"ng-disabled"=>"currentPage == 0", :"ng-click"=>"currentPage = currentPage - 1"}
          Previous
        {{ currentPage + 1 }}/{{ numberOfPages() }}
        %button{:"ng-disabled"=> "currentPage >= filteredParticipants().length/pageSize - 1", :"ng-click"=>"currentPage = currentPage + 1"}
          Next

app/views/participants/show.html.haml
= render 'games/header'
= render partial: 'name_title'
= render 'games/menu'

.soft
  .max-readable-width
    .text--center>
      = link_to 'back', [@game, :participants]
      %br
      = link_to 'edit', [:edit, @game, @participant] if current_admin
      %br
    .grid__item.one-half.text--left>
      - unless @participant.twitter.blank?
        = 'Twitter: '
        = link_to @participant.twitter, @participant.twitter_link
        %br
        %br
      - unless @participant.youtube.blank?
        = 'Youtube: '
        = link_to @participant.youtube, "http://www.youtube.com/#{@participant.youtube}"
        %br
        %br
      - unless @participant.wiki.blank?
        = 'Wiki: '
        = link_to @participant.wiki, "http://wiki.teamliquid.net/smash/#{@participant.wiki}"
        %br
        %br

      - unless @participant.team_names.blank?
        = 'Teams: '
        - @participant.teams.each do |team|
          = link_to team.name, game_participants_path(@game, team: team)
        %br
        %br

      = 'Location: ' + @participant.location unless @participant.location.blank?

      - if @participant.characters.count > 0
        %br
        %br
        = 'He plays: '
        - CharacterParticipant.where(participant_id: @participant.id).count.times do |rank|
          - character_slug = CharacterParticipant.where(participant_id: @participant.id).find_by_rank(rank + 1).character.slug
          = link_to image_tag("#{@game.slug}/#{character_slug}.png"), game_participants_path(@game, character: character_slug)
    .grid__item.one-half.text--left>
      = "Score: #{@participant.score}"
      %br
      %br
      - link = 'Global rank: ' + @participant.global_rank.ordinalize
      = link_to link, game_participants_path(@game)
      %br
      - if @participant.country
        - link = @participant.country + ' rank: ' + @participant.country_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country)
      %br
      - if @participant.state
        - link = @participant.state + ' rank: ' + @participant.state_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state)
      %br
      - if @participant.sub_state
        - link = @participant.sub_state + ' rank: ' + @participant.sub_state_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state, sub_state: @participant.sub_state)
      %br
      - if @participant.city
        - link = @participant.city + ' rank: ' + @participant.city_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state, sub_state: @participant.sub_state, city: @participant.city)
      %br
      - if next_target = @participant.next_target
        = "#{@participant.name}'s next target is "
        = link_to next_target.name, [@game, next_target]
      %br
      - if training_partners = @participant.training_partners
        = 'He should train with '
        - training_partners.each do |player|
          = link_to player.name + ' ', [@game, player]


.soft
  .max-readable-width
    %h5.text--center= 'Tournaments (only the best 5 scores count)'
    %br
    .grid
      - @results.sort_by{ |r| r.tournament_score }.reverse.each do |result|
        .grid__item.one-half.text--right
          = link_to "#{result.tournament_score.round(3)}", [@game, result.tournament]          
        .grid__item.one-half.text--left>
          = link_to "#{result.rank.ordinalize} @ #{result.tournament.name}", [@game, result.tournament]

        

app/views/participants/show.html.slim
= render partial: 'menu'
.soft
  .max-readable-width
    .grid__item.one-half.text--left
      - unless @participant.twitter.blank?
        => 'Twitter: '
        = link_to @participant.twitter, @participant.twitter_link
        br
        br
      - unless @participant.youtube.blank?
        => 'Youtube: '
        = link_to @participant.youtube, "http://www.youtube.com/#{@participant.youtube}"
        br
        br
      - unless @participant.wiki.blank?
        => 'Wiki: '
        = link_to @participant.wiki, "http://wiki.teamliquid.net/smash/#{@participant.wiki}"
        br
        br

      - unless @participant.team_names.blank?
        => 'Teams: '
        - @participant.teams.each do |team|
          => link_to team.name, game_participants_path(@game, team: team)
        br
        br

      = 'Location: ' + @participant.location unless @participant.location.blank?

      - if @participant.characters.count > 0
        br
        br
        => 'He plays: '
        - CharacterParticipant.where(participant_id: @participant.id).count.times do |rank|
          - character_slug = CharacterParticipant.where(participant_id: @participant.id).find_by_rank(rank + 1).character.slug
          => link_to image_tag("#{@game.slug}/#{character_slug}.png"), game_participants_path(@game, character: character_slug)


    .grid__item.one-half.text--right
      = "Score: #{@participant.score}"
      br
      br
      - link = 'Global rank: ' + @participant.global_rank.ordinalize
      = link_to link, game_participants_path(@game)
      br
      - if @participant.country
        - link = @participant.country + ' rank: ' + @participant.country_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country)
      br
      - if @participant.state
        - link = @participant.state + ' rank: ' + @participant.state_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state)
      br
      - if @participant.sub_state
        - link = @participant.sub_state + ' rank: ' + @participant.sub_state_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state, sub_state: @participant.sub_state)
      br
      - if @participant.city
        - link = @participant.city + ' rank: ' + @participant.city_rank.ordinalize
        = link_to link, game_participants_path(@game, country: @participant.country, state: @participant.state, sub_state: @participant.sub_state, city: @participant.city)
      br
      - if next_target = @participant.next_target
        = "#{@participant.name}'s next target is "
        = link_to next_target.name, [@game, next_target]
      br
      - if training_partners = @participant.training_partners
        = 'He should train with '
        - training_partners.each do |player|
          = link_to player.name + ' ', [@game, player]


.soft
  .max-readable-width
    h3.text--center= 'Tournaments (only the best 5 scores count)'
    br
    .grid
      - @results.sort_by{ |r| r.tournament_score }.reverse.each do |result|
        .grid__item.one-quarter.text--center
          = link_to "#{result.tournament_score.round(3)}", [@game, result.tournament]          
        .grid__item.three-quarters.text--left>
          = link_to "#{result.rank.ordinalize} @ #{result.tournament.name}", [@game, result.tournament]

        