config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords]
  resources :games do
    member do
      get :compute
    end
    resources :statistics
    resources :tournaments
    resources :participants
  end

  root 'home#show'
end

app/views/layouts/_admin.html.slim
div style='background-color: black;'
  - if current_admin.present?
    .text--right.small.soft--right
      = link_to "Logged as #{current_admin.email}"
      | -- 
      = link_to 'Logout', destroy_admin_session_path, method: :delete
  - else
    .text--right.small.soft--right
      = link_to 'Admin Login', new_admin_session_path  

app/views/layouts/_analytics_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57203747-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57203747-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.slim
doctype html
html
  head
    title= 'PoilonsRanking'
    meta content='width=device-width, initial-scale=1.0' name='viewport'
    script type='text/javascript' src='https://maps.googleapis.com/maps/api/js?sensor=false'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if notice
      .notice
        = notice
    - if alert
      .alert
        = alert
    = yield
= render partial: 'layouts/analytics_footer'